<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKZ7FaKJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKZ7FaKJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKZ7FaKJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKZ7FaKJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKZ7FaKJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KZ7FaKJ',
    'container.build_id' => '453f4f1d',
    'container.build_time' => 1562420919,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKZ7FaKJ');
