<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMDFgaB9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMDFgaB9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMDFgaB9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMDFgaB9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMDFgaB9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MDFgaB9',
    'container.build_id' => '2630368b',
    'container.build_time' => 1562420869,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMDFgaB9');
